quarkus.live-reload.watched-resources=photon_example.wasm

# The "photon" module that we use to showcase how to add a Wasm module context sourced from
# a static file, see src/main/resources/photon_example.wasm
quarkus.chicory.modules[0].name = org.acme.Photon
quarkus.chicory.modules[0].wasm-file = /home/fburzigo/projects/git/andreaTP/quarkus-photon-demo/src/main/resources/photon_example.wasm
quarkus.chicory.modules[0].compiler.interpreter-fallback=warn
