#quarkus.live-reload.watched-resources=photon_example.wasm

# The "photon" module that we use to showcase how to add a Wasm module context sourced from
# a static file, see src/main/resources/photon_example.wasm, or from a classpath resource, as it's done here
quarkus.chicory.modules.photon.name = org.acme.Photon
quarkus.chicory.modules.photon.wasm-resource= photon_example.wasm
quarkus.chicory.modules.photon.compiler.interpreter-fallback=warn
