quarkus.live-reload.watched-resources=photon_example.wasm

# The "photon" module that we use to showcase how to add a Wasm module context sourced from
# a static file, see src/main/resources/photon_example.wasm
quarkus.chicory.wasm-modules.modules[0].id = photon
quarkus.chicory.wasm-modules.modules[0].static-file-path = /home/fburzigo/projects/git/andreaTP/quarkus-photon-demo/src/main/resources/photon_example.wasm
# We also set the generated Was API factory information, which will be used by Quarkus-chicory in
# production mode, to leverage generated classes and avoid runtime compilation
quarkus.chicory.wasm-modules.modules[0].factory-class-name = org.acme.Photon
quarkus.chicory.wasm-modules.modules[0].factory-method-name = create
